#!/usr/bin/osascript
on run argv
  set dir to quoted form of (first item of argv)

  if application "iTerm" is running then
  	set wasRunning to true
  else
    set wasRunning to false
  end if

  tell application "iTerm"
    activate

  	if wasRunning then
  		tell current window
  			create tab with default profile
  		end tell
  	end if

  	tell last session of current tab of current window
  		set name to "RStudio Session"
  		write text "cd " & dir & "; clear"
  	end tell
  end tell
end run
