#!/usr/bin/env bash

clear

echo 'Updating brew...'
brew update 
brew upgrade 
brew cleanup --all -y
echo 'Brew update complete.'
echo ''
echo ''

echo 'Updating Anaconda...'
conda upgrade --all -y
conda clean --all -y
echo 'Anaconda update done.'